Shortened some which.fish completions.
fish-shell/fish-shell pull request #10347
Opened 2024-03-07 08:28 UTC by amiyzku

## Description

Shortened some which.fish completions.

Related to https://github.com/fish-shell/fish-shell/issues/6981.

## TODOs:

- [ ] Changes to fish usage are reflected in user documentation/manpages.
- [ ] Tests have been added for regressions fixed
- [ ] User-visible changes noted in CHANGELOG.rst

2024-03-09 04:01 UTC, mqudsi commented on share/completions/which.fish
> +    complete -c which -l skip-tilde -d "Skip directories in PATH starting with a tilde and executables in the HOME directory"
Can shorten this further to "starting with tilde and executables in \$HOME"

2024-03-09 04:02 UTC, mqudsi commented on share/completions/which.fish
> +    complete -c which -l show-dot -d "If a directory in PATH starts with a dot and a matching executable was found, print './programname'"
"For matches in PATH dirs that start with a dot, print './programname'" is shorter

2024-03-09 04:03 UTC, mqudsi reviewed
This is fine, but I made some suggestions to shorten it further. Also you can change "directories" to "dirs" everywhere *if you like*.

2024-03-09 04:50 UTC, amiyzku commented
Thank you for the review! I've incorporated your feedback and made the suggested changes. Please take another look and let me know if there's anything else that needs to be addressed.

2024-03-09 21:26 UTC, mqudsi requested changes
FYI I had intentionally written `\$HOME` instead of `$HOME` because in a double quoted (`"`) string, `$HOME` will expand to the actual value of `$HOME`. You need to either escape the `$` sign like `\$` or use `'` single quotes instead of double quotes `"`.

2024-03-10 01:46 UTC, amiyzku commented
Thank you for the review! I've updated the code to escape  as suggested.

2024-03-10 02:52 UTC, mqudsi approved these changes

2024-03-10 02:52 UTC, merged