[RUSTSEC-2020-0070] Bump serial_test dependency to 1.0.0
fish-shell/fish-shell pull request #10390
Opened 2024-03-23 06:29 UTC by Pi-Cla

## Description
The current version of serial_test we use (0.4.0) depends on parking_lot 0.10.2 which in turn depends on lock_api 0.3.4.
This version of lock_api is vulnerable to [RUSTSEC-2020-0070](https://rustsec.org/advisories/RUSTSEC-2020-0070) This was patched in lock_api 0.4.2 but we need to update serial_test to get the update.

2024-03-23 06:39 UTC, mqudsi requested changes
I've applied it locally and confirmed that no older versions of the lock_api crate remain with this patch. 

Can you please re-submit this patch without the formatting changes to the toml file as it's a one-line change but it looks like a lot more currently.

2024-03-23 06:50 UTC, mqudsi approved these changes

2024-03-23 10:01 UTC, merged

2024-03-29 00:46 UTC, zanchey commented
This pulled in a huge chunk of dependencies, including some previously removed (eg jobserver) and a bunch of Windows targets.

2024-03-29 04:27 UTC, krobelus commented
I'll remove the dependency, it must be a simple one-liner that takes a lock

2024-03-30 16:45 UTC, zanchey commented
https://github.com/palfrey/serial_test/issues/6 - `parking_lot` was pulled in for its reentrant lock support, which didn't exist in std back then and isn't stabilised yet (https://doc.rust-lang.org/nightly/std/sync/struct.ReentrantLock.html)

2024-03-30 16:48 UTC, zanchey commented
Slimmed things down a bit with 792eff42b