change cd to handle not readable directories: chdir+open instead of open+fchdir
fish-shell/fish-shell pull request #10436
Opened 2024-04-11 12:13 UTC by TheJonny

The previous code for the cd builtin used open(.., O_RDONLY) + fchdir to change the working directory. This fails, if the user has no read permission on the directory (but has the x permission). Now we first chdir and then try to open the new workin directory. this might fail, but in this case cd was already successful.

The alternative would be to use O_PATH instead of O_RDONLY, but this is not portable. As an improvement, we could use O_PATH for supported platforms later.

## Description

Talk about your changes here.

Fixes issue #

## TODOs:

- [ ] Changes to fish usage are reflected in user documentation/manpages.
- [ ] Tests have been added for regressions fixed
- [ ] User-visible changes noted in CHANGELOG.rst

2024-04-11 16:16 UTC, TheJonny commented
should we note the change in CHANGELOG.rst?
should we drop fds::wopen_dir (now unused) or keep it for future use?

2024-04-12 13:03 UTC, TheJonny commented
The failed test is from the additional stderr line, from the testcase below.
`Unable to open the current working directory: Permission denied`
Do we want this output in cd?
also without this patch `mkdir a; chmod -r a; sh -c 'cd a; fish'` triggers this message

2024-04-14 22:21 UTC, ridiculousfish requested changes
Thank you for the PR. The reason we store the file descriptor in the parser is that subprocesses will be implemented using multiple threads, each with their own fd for the cwd. For that reason we should not rely on the processes's implicit cwd (i.e. `chdir`) for anything, outside of startup, where we discover where we are.

That said, I would definitely like to see this fixed. I'm fine with using `O_PATH` on Linux (supported since 2014), and `O_SEARCH / O_EXEC` on BSDs / macOS. We can keep `O_RDONLY` as a fallback for any other platforms.

Note Nix doesn't seem to have up-to-date support for `O_SEARCH / O_EXEC` so we may need to fall back to libc or hard-coded constants.

2024-04-14 23:10 UTC, TheJonny commented
the current implementation (without this PR) relies on the process cwd when opening relative paths before fchdir, so the implementation in this PR using chdir with the same relative path should not worsen anything right now.

2024-04-14 23:17 UTC, TheJonny commented
when using O_PATH / O_SEARCH, should we rename the `[w]open_dir` functions to `open_path` or add the flags as argument, to make clear when it is possible to readdir on the returned file descriptor?

2024-04-14 23:50 UTC, TheJonny commented
ok fascinating - macos and freebsd 13 have indeed O_SEARCH, it's just not in the manpages.

so i will have some `#[cfg]` fun.

2024-04-15 10:35 UTC, TheJonny commented
@ridiculousfish i implemented the alternative in #10442

2024-05-11 20:47 UTC, closed without merging