Return true if there was an autosuggestion to accept
fish-shell/fish-shell pull request #10608
Opened 2024-07-09 00:25 UTC by diniamo

## Description

Return true from `accept-autosuggestion` if there was an autosuggestion to accept, just like `suppress-autosuggestion`. 

## TODOs:

- [x] Changes to fish usage are reflected in user documentation/manpages.
- [ ] Tests have been added for regressions fixed
- [x] User-visible changes noted in CHANGELOG.rst

2024-07-10 21:50 UTC, mqudsi commented on CHANGELOG.rst
> +- The `accept-autosuggestion` input function now returns true when there was something to accept.
Pedantically, I think the real change is that it now returns false if there *wasn't* something to accept.

2024-07-10 21:53 UTC, mqudsi requested changes
I left a comment about changing the documentation to be "returns true when.." to "returns false when..", if you don't mind changing that.

It would also be nice for this to be accompanied by a test. You can probably model this directly off [the recent addition of a pexpect test](https://github.com/fish-shell/fish-shell/commit/936f7d9b8d3faeb49de4e617d76eaedabce09aaa) for `commandline --showing-suggestion`.

2024-07-10 22:01 UTC, diniamo commented
I'm really not sure how to write the test, so I would appreciate it if someone did it for me.

2024-07-15 00:43 UTC, mqudsi commented
In what context are you using this? Can you give an example of how you are invoking this input function? (relevant for how the status code is returned)

2024-10-05 21:44 UTC, closed without merging

2024-10-05 21:47 UTC, diniamo commented
Thanks!

2024-10-22 06:25 UTC, krobelus commented
going through the changelog I realized we already have `commandline --showing-suggestion` which should be the canonical version (because it's more flexible) so I'll not changelog this. In fact we can completely get rid of `and` and `or` special bind functions, deprecate them and IMO remove them from docs.