Master
fish-shell/fish-shell pull request #10691
Opened 2024-08-29 14:29 UTC by cedricbuild

## Description

Talk about your changes here.

Fixes issue #

## TODOs:

- [x] Changes to fish usage are reflected in user documentation/manpages.
- [x] Tests have been added for regressions fixed
- [x] User-visible changes noted in CHANGELOG.rst

2024-09-14 22:14 UTC, ridiculousfish requested changes
Thanks for this PR! Some things to fix.

2024-09-14 22:14 UTC, ridiculousfish commented on tests/pexpects/job_summary.py
> +sys.path.append("/home/cedric/projects/fish-shell/build_tools/")
Please remove these

2024-09-14 22:14 UTC, ridiculousfish commented on share/functions/fish_job_summary.fish
> +            set message (printf ( _ "fish: Job %s, '%s' has Non Zero status code:%s\n" ) $job_id $cmd_line $signal_desc)
As `$signal_desc` may now be either the exit code or the status value, please update the "docstring" at the top of the function, and rename the variable.

As for the message, I suggest just extending the ENDED message:

```
set message (printf ( _ "fish: Job %s, '%s' has ended with status %d\n" ) $job_id $cmd_line $status_num)
```

2024-09-14 22:14 UTC, ridiculousfish commented on src/proc.rs
>              // We are summarizing a process which exited with a signal.
This comment is no longer accurate, please update it

2024-12-29 14:34 UTC, faho commented
Closing this for lack of response.

2024-12-29 14:34 UTC, closed without merging