vi mode: support increment/decrement of numbers
fish-shell/fish-shell pull request #10704
Opened 2024-09-06 02:54 UTC by DevAtDawn

## Description
use ctrl+x ctrl+a to increase/decrease a number

Fixes issue #8320

## TODOs:

- [ ] Changes to fish usage are reflected in user documentation/manpages.
- [ ] Tests have been added for regressions fixed
- [ ] User-visible changes noted in CHANGELOG.rst

2024-09-06 13:32 UTC, d-e-s-o commented
For what it's worth, I had also gotten my own version implemented by now, just haven't gotten around to upstreaming it: https://github.com/fish-shell/fish-shell/compare/master...d-e-s-o:fish-shell:topic/increment-decrement

Haven't looked at the changes at hand to judge which one is nicer.

2024-09-14 20:52 UTC, ridiculousfish requested changes
Thank you for tackling this. Please add a test if possible to the bind.py tests, [in the vi section](https://github.com/fish-shell/fish-shell/blob/a6c8cd6e85f5f7092b47e28e9963cb3268a2b5be/tests/pexpects/bind.py#L71)

2024-09-14 20:52 UTC, ridiculousfish commented on share/functions/increment_decrement.fish
As this function is specific to these key bindings, let's name it something unwieldy like `__fish_inc_dec_number_under_cursor`.

2024-09-14 20:52 UTC, ridiculousfish commented on share/functions/increment_decrement.fish
> +    set current_buffer (commandline -b)
Please add comments explaining what is happening, and how to call the function

2024-12-20 21:01 UTC, closed without merging