simplified compute_gaps
fish-shell/fish-shell pull request #10917
Opened 2024-12-18 17:18 UTC by sharma-shray

## Description

Talk about your changes here.

Fixes issue #

## TODOs:

- [ ] Changes to fish usage are reflected in user documentation/manpages.
- [ ] Tests have been added for regressions fixed
- [ ] User-visible changes noted in CHANGELOG.rst

2025-01-03 23:25 UTC, mqudsi commented
I think this PR hasn't been touched because it's not immediately obvious if there are any subtle changes to the algorithm. 

Do you mind adding some unit tests to illustrate that behavior is unchanged?

2025-01-03 23:26 UTC, mqudsi requested changes
I think this PR hasn't been touched because it's not immediately obvious if there are any subtle changes to the algorithm.

Do you mind adding some unit tests to illustrate that behavior is unchanged?

2025-01-20 00:55 UTC, epidemian commented on src/bin/fish_indent.rs
> +        .collect();
A little idea in regards to code simplification: using some shorter `.map()`s and `.filter()`s instead of a general `.filter_map()`, those dangling `else { None }`s could be avoided

```rust
        let mut tok_ranges: Vec<SourceRange> = Traversal::new(self.ast.top())
            .filter(|node| node.category() == Category::leaf)
            .map(|leaf| leaf.source_range())
            .filter(|range| range.length() > 0)
            .collect();
```

I find this a bit easier to follow than the nested `if`s :)

(BTW, i cannot vouch for the correctness of these changes; this is just a drive-by comment.)

2025-01-20 00:58 UTC, epidemian commented on src/bin/fish_indent.rs
> +    assert!(tok_ranges.is_sorted_by(|x, y| Some((x.start(), x.length()).cmp(&(y.start(), y.length())))));
Oh, and if this is comparing tuples of the same things, `(range.start(), range.length())`, it should be the same to use `.is_sorted_by_key`:

```suggestion
    assert!(tok_ranges.is_sorted_by_key(|r| (r.start(), r.length())));
```

2025-03-13 17:02 UTC, faho commented
No reaction for a while and merge conflicts with master, closing.

If you get back to it we can reopen.

2025-03-13 17:02 UTC, closed without merging