completions: Add support for lightdm and dm-tool commands
fish-shell/fish-shell pull request #7624
Opened 2021-01-12 16:11 UTC by woodsb02

Improve completion for the LightDM display manager, by adding support for the lightdm and dm-tool commands.

Refer to the [lightdm(1)](https://man.freebsd.org/lightdm) and [dm-tool(1)](https://man.freebsd.org/dm-tool) manpages for details of the command syntax.

2021-01-12 16:18 UTC, faho requested changes

2021-01-12 16:18 UTC, faho commented on share/completions/dm-tool.fish
> +set -l session_users "(dm-tool list-seats | grep UserName | sed 's/.*UserName=//' | sed 's/\'//g')"
This should use our `string` builtin:

```fish
dm-tool list-seats | string replace -rf '.*UserName=' '' | string trim -c "'"

2021-01-12 23:09 UTC, woodsb02 commented on share/completions/dm-tool.fish
> +set -l session_users "(dm-tool list-seats | grep UserName | sed 's/.*UserName=//' | sed 's/\'//g')"
Done in 384a54e
Thanks

2021-01-13 13:37 UTC, merged

2021-01-13 13:37 UTC, faho commented
Merged, thanks!