Shorten various long descriptions
fish-shell/fish-shell pull request #7752
Opened 2021-02-27 18:03 UTC by bjia56

## Description

Tweaks or rephrases long descriptions for:
 - `git.fish`
 - `gitk.fish`
 - `jest.fish`
 - `lsof.fish`
 - `lsusb.fish`
 - `minikube.fish`

Makes progress on #6981 

:shipit: 

## TODOs:

- [ ] Changes to fish usage are reflected in user documentation/manpages.
- [ ] Tests have been added for regressions fixed
- [ ] User-visible changes noted in CHANGELOG.rst

2021-02-27 18:25 UTC, faho requested changes

2021-02-27 18:25 UTC, faho commented on share/completions/git.fish
> +complete -c git -n '__fish_git_using_command diff show range-diff' -s G -d 'Look for differences where <regex> matches the patch text''s added/removed lines'
Doubling up single quotes just closes and then reopens the quotes. (I think it works like this in rc?)

You'll have to escape it with `\\` or use double-quotes for the outside.

2021-02-27 18:25 UTC, faho commented on share/completions/git.fish
> +complete -c git -n '__fish_git_using_command filter-branch' -s f -l force -d 'Force filter branch to start even w/ refs in refs/original or existing temp dir'
This is one of those descriptions where we're so close to the git documentation I have no actual idea what it means.

It's possible this is talking about an unclean shutdown kind of situation? Does filter-branch use the refs/original directory to store the branches before filtering, and a temp dir to work in, and so if those exist that indicates that you tried to filter-branch and didn't complete it?

But as it stands the "Force filter branch to start" is the part that wastes characters, so how about

    Filter even with refs in refs/original or existing temp directory

That's 65 characters compared to the original 85 and your 79, and it even ditches the awkward "w/".

2021-02-27 18:25 UTC, faho commented on share/completions/git.fish
> +complete -c git -n '__fish_git_using_command log' -l all -d 'Pretend that all refs in refs/ are listed on the cmd line as <commit>'
How about "Show log for all branches, tags and remotes"?

That's what people use it for, in practice. "refs in refs/" is git-ese.

2021-02-27 18:25 UTC, faho commented on share/completions/git.fish
> +complete -f -c git -n '__fish_git_using_command log' -l branches -d 'Pretend that all refs in refs/heads are listed on the cmd line as <commit>'
This would then be "Show log for all matching branches" - it can take an optional argument to match branches.

2021-02-27 18:25 UTC, faho commented on share/completions/git.fish
> +complete -c git -n '__fish_git_using_command log' -l reflog -d 'Pretend that all objs included in reflogs are listed on the cmd line as <commit>'
"Show log for all reflog entries"

2021-02-27 18:25 UTC, faho commented on share/completions/git.fish
> +complete -x -c git -n '__fish_git_using_command log' -l glob -d 'Pretend that all refs matching shell glob are listed on the cmd line as <commit>'
"Show log for all matching branches, tags and remotes"

2021-02-27 18:25 UTC, faho commented on share/completions/git.fish
> +complete -f -c git -n '__fish_git_using_command format-patch' -l textconv -d "Allow external txt conv filters for binary files (Resulting diff is unappliable)"
Just "filters" or "conversion filters" should do, I think?

"Allow external filters for binary files (Resulting diff is unappliable)"

2021-02-27 18:26 UTC, faho commented on share/completions/git.fish
> +complete -c git -n '__fish_git_using_command diff show range-diff' -s G -d 'Look for differences where <regex> matches the patch text''s added/removed lines'
Also just "the patch's added/removed lines" should work? The "patch text" part is weird and I think unnecessary.

2021-02-27 23:24 UTC, bjia56 commented
@faho thanks for the quick review! I've made the changes you requested.

2021-02-28 11:12 UTC, merged

2021-02-28 11:13 UTC, faho commented
Merged, thanks!