completions: shorten descriptions for p4
fish-shell/fish-shell pull request #8647
Opened 2022-01-15 21:47 UTC by dundargoc

Work on https://github.com/fish-shell/fish-shell/issues/6981

2022-01-16 05:52 UTC, floam commented
Love any assistance shortening completion descriptions! Just one minor nit regarding the addition of a ending period in one I noticed. 

We don't really have a written down style guide for descriptions, but this is one thing we've tried to not add more of recently. 

If you feel motivated, when it comes to these, we'd love even much more aggressive abridgment if you are up for it - the existing p4 copy doesn't  represent I think what anyone actually considers the spartan ideal length-wise, these were likely derived from wordy documentation.

Thanks for helping out in this regard.

2022-01-16 07:22 UTC, floam requested changes

2022-01-16 08:49 UTC, zanchey commented on share/completions/p4.fish
> +complete -c p4 -n __fish_p4_not_in_command -s s -d 'Prepends a prefix (e.g. "info: ") to each line of output. Mainly for scripting.'
This could just be "Prefix for each line" if you want to really shorten it

2022-01-16 08:49 UTC, zanchey commented on share/completions/p4.fish
> +complete -c p4 -n __fish_p4_not_in_command -s r -x -d 'Number of times to retry a command (notably, p4 sync) if the network times out.'
This could just be "Number of retry attempts"

2022-01-16 11:23 UTC, floam commented on share/completions/p4.fish
>  complete -c p4 -n __fish_p4_not_in_command -s I -d 'Specify that progress indicators, if available, are desired. This option is not compatible with the -s and -G options'
Just as an example of "more aggressive"... this could have been just "show process indicators"

2022-01-16 11:24 UTC, floam commented on share/completions/p4.fish
>  complete -c p4 -n __fish_p4_not_in_command -s G -d 'Causes all output (and batch input for form commands with -i) to be formatted as marshalled Python dictionary objects'
"python output"

2022-01-16 13:13 UTC, dundargoc commented
So we're aiming for MINIMAL minimal :). Gotcha.

2022-01-16 13:16 UTC, dundargoc commented
I had <80 characters or less as a goal but that's probably too generous in hindsight. I'll go through the descriptions again and *try* to get below 60 unless it's completely incomprehensible (should be feasible if we can ignore writing complete sentences).

2022-01-16 14:07 UTC, floam commented
> So we're aiming for MINIMAL minimal :). Gotcha.

I think so. It's bad if at runtime we're seeing completions where everything is getting truncated with the terminal being 80 characters wide (that is **not** the same as 80 character descriptions), but even less is better: the pager can start presenting 2 or 3 column layouts, or maybe even if it's not down to 2 columns at in a 80 column maybe it will at 100.

Looking at the p4 documentation I am seeing they managed to get short concise descriptions in their own usage output.

2022-01-16 14:28 UTC, dundargoc commented
Yes, I think I'm done. Mind taking a look again?

2022-01-17 12:31 UTC, dundargoc commented
> Looking at the p4 documentation I am seeing they managed to get short concise descriptions in their own usage output.

@floam Do you have a link? I can only find the same descriptions as in the file.

2022-01-17 12:38 UTC, floam commented
I think it was this http://clanmills.com/articles/perforce/p4_man.html

2022-01-17 16:37 UTC, floam commented
Very nice

2022-01-17 18:08 UTC, dundargoc commented
All current p4 completions are under 60 characters. Should be sufficient IMO, especially considering the infinite number of commands p4 has. That and I think there are more worthwhile completions to focus on.

2022-01-17 19:05 UTC, floam commented
Great work @dundargoc!

2022-01-17 19:05 UTC, floam approved these changes

2022-01-17 19:06 UTC, merged