Shortened quilt definitions
fish-shell/fish-shell pull request #8667
Opened 2022-01-27 19:23 UTC by T19700

shortens the definitions found in quilt.fish to around 70 characters or less (one exception at 80). I also fixed spacing issues and made grammar and capitalization consistent.

Worked on issue #6981 

This is my first change time working with GitHub in this way. Let me know if any edit need to be made.

2022-01-27 20:02 UTC, faho requested changes

2022-01-27 20:02 UTC, faho commented on share/completions/quilt.fish
> +complete -c quilt -a grep -r --no-file -d "Grep through source files recursively (skips patches and quilt meta-information)"
We already know that it's source files, no need to list patches and meta-stuff specifically. So just "grep through source recursively"?

2022-01-27 20:02 UTC, faho commented on share/completions/quilt.fish
> +complete -c quilt -a refresh -r -d "Refreshes the given patch, or the topmost patch by default"
We use the imperative mood - "Refresh the given patch...". This consistently saves characters ("refresh" vs "refreshes")

2022-01-27 20:02 UTC, faho commented on share/completions/quilt.fish
> +complete -c quilt -a refresh -r -d "Refreshes the given patch, or the topmost patch by default"
(this goes for the rest as well!)

2022-01-27 20:02 UTC, faho commented on share/completions/quilt.fish
> +complete -c quilt -a setup -r -d "Initializes a source tree from an rpm spec file or a quilt series file"
Maybe remove the first "file"? "Initialize a source tree from an rpm spec or quilt service file"?

2022-01-27 20:20 UTC, T19700 commented on share/completions/quilt.fish
> +complete -c quilt -l quiltrc -r --no-file -d "Specify the file to Run Control file to use"
would you like me to remove the "--no-file"?

2022-01-27 20:33 UTC, faho commented on share/completions/quilt.fish
> +complete -c quilt -l quiltrc -r --no-file -d "Specify the file to Run Control file to use"
Unless you know that it's not needed, not right now.

I'm just musing that we should take a look at it, but until someone does that I'd always trust the initial author, as they typically know the thing the completions are for (that's why they wrote them!).

2022-01-27 20:33 UTC, T19700 commented on share/completions/quilt.fish
> +complete -c quilt -l quiltrc -r --no-file -d "Specify the file to Run Control file to use"
I fixed the rc definition, just let me know about the "--no-file" and ill fix that if you want me to!

2022-02-08 19:19 UTC, merged

2022-02-08 19:19 UTC, faho commented
Merged, sorry for the delay!