Add reference to abbreviations
fish-shell/fish-shell pull request #9226
Opened 2022-09-20 21:49 UTC by lucatrv

2022-09-21 03:58 UTC, mqudsi requested changes

2022-09-21 03:58 UTC, mqudsi commented on doc_src/tutorial.rst
> +.. [#] fish also provides :ref:`abbrevisations <interactive-abbreviations>`, through the :ref:`abbr <cmd-abbr>` command.
You have a typo here.

2022-09-21 12:53 UTC, mqudsi commented
I’m not sure if we need two footnotes here. Can’t we just merge both into one? Happy to hear your thoughts.

2022-09-21 19:50 UTC, lucatrv commented
> I’m not sure if we need two footnotes here. Can’t we just merge both into one? Happy to hear your thoughts.

Yes I agree they could be merged into a single footnote. IMHO the only drawback is that abbreviations would be a little less evident in the text, while I think they are very useful and maybe they would deserve even a full paragraph of the tutorial in future... Bottom line, for me both options are ok, please let me know which one you prefer.
Thanks for asking my opinion BTW.

2022-09-23 20:51 UTC, lucatrv commented
> Ok, let's merge the paragraphs for now and we can always write more about `abbr`, move it to its own paragraph, etc. in the future.

Please let me know if I need to do anything else

2022-09-24 03:30 UTC, mqudsi commented
Sorry, I can see how my comment could have been taken to signal merging the PR. I meant can you merge the two footnotes into one paragraph.

2022-09-24 13:08 UTC, lucatrv commented
> Sorry, I can see how my comment could have been taken to signal merging the PR. I meant can you merge the two footnotes into one paragraph.

Oh, my bad! :)

2022-09-24 22:15 UTC, ridiculousfish commented
Merged as 064699cade2bba9f37b1a90317f7d370b8481030, thank you.

2022-09-24 22:15 UTC, closed without merging

2022-09-24 22:16 UTC, ridiculousfish commented
I implemented mqudsi's feedback and merged the footnotes together.