completions: added systemd-cryptenroll
fish-shell/fish-shell pull request #9325
Opened 2022-11-02 17:55 UTC by exploide

## Description

Added completions for `systemd-cryptenroll` which allows to configure LUKS2 key slots with FIDO2/PKCS11/TPM2 devices for key unlock.

## TODOs:

- [ ] Changes to fish usage are reflected in user documentation/manpages.
- [ ] Tests have been added for regressions fixed
- [ ] User-visible changes noted in CHANGELOG.rst

2022-11-02 18:13 UTC, mqudsi reviewed
Thanks for submitting this completion. 

Are there any subcommands that require `sudo`? Does enumerating devices ever required `sudo`?

2022-11-02 18:25 UTC, exploide commented
The final command should need to be run with `sudo` I guess. But the enumeration was done without elevated privileges. This should work.

2022-11-06 17:23 UTC, mqudsi commented on share/completions/systemd-cryptenroll.fish
> +complete -c systemd-cryptenroll -l tpm2-device -xa "(__fish_cryptenroll_tpm2_devices)" -d "Enroll a TPM2 security chip"
e.g. using `-kxa` instead of `-xa` here.

2022-11-06 17:24 UTC, mqudsi requested changes
That's good. I know some other hardware enumeration completions require sudo for the completions themselves which is harder to handle.

Question for you:

In all the `__fish_cryptenroll_xxxx_devices` functions, you have an actual list of enumerated devices then two hard-coded options (`auto` and `list`). Currently they'll be munged in with the actual device names and all of them displayed in alphabetical order. I think you would prefer to use `-k` (see the annotated example) so that these two lines are shown after all the actual device name completions?

2022-11-06 17:34 UTC, mqudsi commented
I see that you added `-kxa` everywhere. The only question is if the output of `systemd-cryptenroll --xxxx-device=list` is already sorted (by some strict order even if not alphabetic) or if you need to sort it yourself (`| sort`) now that fish's pager won't do the sort for you.

2022-11-06 17:37 UTC, exploide commented
> I think you would prefer to use -k (see the annotated example) so that these two lines are shown after all the actual device name completions?

I don't really care whether the two default keywords are sorted before or after the devices and in most cases you have only one device available anyway. However it would be odd if it gets sorted in between the default keywords, so I added the `-k` option as requested. Though this probably wouldn't have happened because the devices usually start with `/dev` and `/` comes alphabetically before `auto`.

> I see that you added -kxa everywhere. The only question is if the output of systemd-cryptenroll --xxxx-device=list is already sorted (by some strict order even if not alphabetic) or if you need to sort it yourself (| sort) now that fish's pager won't do the sort for you.

I don't know as I don't have more than one of each respective device class. And you typically don't have many of them plugged in simultaneously anyway.

2022-11-06 17:38 UTC, mqudsi commented
That makes sense to me. I'll merge this, thanks for the quick revisions and sorry for the review delay.

2022-11-06 17:38 UTC, merged