Updated hostnamectl completions
fish-shell/fish-shell pull request #9383
Opened 2022-11-26 13:39 UTC by exploide

## Description

`hostnamectl` has been changed some time ago. The subcommands have different names and there is a bit of new functionality. I updated the completions to conform with the new behavior.

## TODOs:

- [ ] Changes to fish usage are reflected in user documentation/manpages.
- [ ] Tests have been added for regressions fixed
- [ ] User-visible changes noted in CHANGELOG.rst

2022-11-26 17:52 UTC, mqudsi commented
So these look like they're breaking changes. Do you know what systems have the old version and what systems have the new version? This ships with the distro and isn't updated out-of-stream, so we can't just assume users have the latest version.

2022-11-26 17:56 UTC, mqudsi requested changes
So these look like they're breaking changes. Do you know what systems have the old version and what systems have the new version? This ships with the distro and isn't updated out-of-stream, so we can't just assume users have the latest version.

2022-11-26 18:52 UTC, EmilySeville7cfg commented on share/completions/hostnamectl.fish
> -set -l commands status set-hostname set-icon-name set-chassis set-deployment set-location
Optional fix: if `--version` or option with the same semantics is available please use it to decide what completions to provide.

2022-11-27 10:26 UTC, exploide commented
Made the subcommand names conditional based on hostnamectl version.

2022-11-29 23:30 UTC, mqudsi commented
Thanks, this looks good.

2022-11-29 23:30 UTC, mqudsi approved these changes

2022-11-29 23:31 UTC, merged