Be more careful about running git and python3 on macOS
fish-shell/fish-shell pull request #9434
Opened 2022-12-27 00:40 UTC by ridiculousfish

See #9345, this is the same idea but simplified and also addressing python. Credit to @floam for most of this work.

macOS Ventura ships the executables `/usr/bin/git` and `/usr/bin/python3`. These are stubs which attempt to look for the real executables; if they are not found then it pops up a dialog to install command line tools. fish runs python3 to populate manpage completions, and also runs git as part of the default prompt, so this dialog pops up a lot. This makes fish nearly unusable on macOS, unless the command line tools are installed.

Unfortunately I've found no easy way to suppress this dialog, other than avoid running these commands. So that's what this does. The fixes (limited to Darwin only):

1. If `git` is `/usr/bin/git` and `xcode-select --print-path` fails, then do not run git in fish_git_prompt.
2. If `python3` is `/usr/bin/python3` and `xcode-select --print-path` fails, do not consider that python from __fish_anypython.

Lastly we fix the git slowness due to the xcrun cache not-yet existing:

3. If `git` is `/usr/bin/git` and `path is "$(xcrun --show-cache-path)"` fails, then running git may be super-slow; do not run git.

I have tested this on a Ventura VM and it correctly suppresses the dialog on first run, both from git and from python3. I have also tested on a 10.9 VM and it continues to work there.

2022-12-27 11:00 UTC, faho requested changes
- Make a variable local
- Can we rely on xcrun and xcode-select existing if uname is Darwin? Possibly add a check

2022-12-27 11:07 UTC, krobelus approved these changes
didn't test it but looks good, thanks everyone.

2022-12-27 11:07 UTC, krobelus commented on share/functions/__fish_anypython.fish
> +        if set py_path (command -s $py)
should be `set -l` to avoid clobbering globals

2022-12-27 11:07 UTC, krobelus commented on share/functions/__fish_anypython.fish
> +                and not xcode-select --print-path &>/dev/null
are `xcode-select` and `xcrun` installed on all Darwin systems?

2022-12-27 11:10 UTC, krobelus commented
heh, I had the same feedback 5 minutes late

2022-12-27 18:49 UTC, ridiculousfish commented on share/functions/fish_git_prompt.fish
> +    if string match -q /usr/bin/git -- "$(command -s git)" && not xcode-select --print-path &>/dev/null
Good suggestions, fixed.

2022-12-27 18:49 UTC, ridiculousfish commented on share/functions/__fish_anypython.fish
> +                and not xcode-select --print-path &>/dev/null
Done

2022-12-27 18:51 UTC, floam commented on share/functions/__fish_anypython.fish
> +                and not xcode-select --print-path &>/dev/null
It exists as far back as we support macOS, at least.

2022-12-27 18:59 UTC, krobelus commented on share/functions/fish_git_prompt.fish
> +        command git --version &>/dev/null &
sorry I think it should be  `disown &>/dev/null` otherwise we'll get an error if `git --version` finishes super fast

2022-12-27 19:39 UTC, faho approved these changes
LGTM

2022-12-27 19:48 UTC, merged

2022-12-28 13:31 UTC, faho commented
For posterity: This was augmented in c844b974b33fdfbd6549e160d6ec2adfc5179dfd to silence the `disown`, so it doesn't print an error message if `git --version` is faster than fish can react.

Notably this happened at least twice on Github Actions - it ended up printing "disown: There are no suitable jobs" in the git.fish test.

(we might want to think of ways of making `disown` easier to use, because we basically always want `disown $last_pid &>/dev/null` for all our uses)

2022-12-31 14:40 UTC, floam commented
I think there is something wrong. I see a delay after deleting the cache file and launching a new fish. It seems like git is running while the `git --version` is yet to complete.

![image](https://user-images.githubusercontent.com/291142/210140443-001bbac7-c979-4b25-a720-5c9bc77b5db4.png)

2022-12-31 15:01 UTC, floam commented
It doesn't happen every time. I believe the mistake is the difference in this PR, it assumes if `path is "$(xcrun --show-cache-path)"` is true, things are ready. But it is either the case that the file can exist before it has been completely written, or there are other things the machinery does after writing the file. The original PR waited for `git --version` to actually complete, which I think is the bullet proof way to do this.

2023-01-01 11:42 UTC, krobelus commented
ok then we should probably wait for `git --version` to complete

2023-01-01 13:42 UTC, krobelus commented
I could not reproduce the slowness. Maybe this has something to do with the fact that I don't have `/Applications/Xcode.app/`.

2023-01-01 13:58 UTC, floam commented
I hit the race maybe 1 in 3 times.

2023-01-01 22:12 UTC, ridiculousfish commented
Yes floam is right, the database file is created early, and is initially empty. So checking for its existence isn't sufficient. This is unfortunately painful to fix: waiting for `git` to complete will address this, but risks creating messages about background jobs if the user exits too early. There's no way to wait on a disowned job.

I also experimented with testing the file size, but this didn't prove reliable - we can catch it mid-write and the race persists.

Probably the best fix would be a way to wait on a disowned job but that's obviously too big for 3.6. Absent any other ideas, I'm inclined to leave things as-is and not try to improve this further.