support prepending please instead of sudo/doas
fish-shell/fish-shell pull request #9635
Opened 2023-03-04 21:00 UTC by AgathaSorceress

## Description

This makes it possible to use `please` with Alt+S instead of `sudo`, if installed, and makes it easier to add support for other similar tools in the future.

## TODOs:

- [ ] Changes to fish usage are reflected in user documentation/manpages.
- [ ] Tests have been added for regressions fixed
- [ ] User-visible changes noted in CHANGELOG.rst

2023-03-05 08:40 UTC, faho requested changes

2023-03-05 08:40 UTC, faho commented on share/functions/__fish_shared_key_bindings.fish
> +    bind --preset $argv \es "for cmd in sudo doas please; if command -q $cmd; fish_commandline_prepend $cmd; break; end; end"
This needs to be single-quoted - you have a variable expansion inside.

2023-03-05 11:49 UTC, merged

2023-03-05 11:49 UTC, faho commented
Merged, thanks!

2023-03-25 14:55 UTC, charego commented
For those at home who have no idea what `please` is: https://github.com/edneville/please ("a sudo clone").