Standardize (un)escape_string_xxx() functions and use rust version
fish-shell/fish-shell pull request #9763
Opened 2023-04-29 04:43 UTC by mqudsi

These are intended to have fixed, reproducible behavior but they were actually
    locale-sensitive and did not necessarily encode non-ASCII input as hex-encoded
    UTF-8 sequences (and instead used whatever encoding wctombb() returned).
    
    Additionally, the unescape functions had code that could not be reached (such as
    checking if c == '_' when c was not ASCII) and duplicate that wasn't needed
    (such as checking for '\0' before checking if a char is a hex digit). The new
    unescape functions might also be stricter in rejecting invalid input.
    
    The escape functions no longer convert the entirety of the wide input into a
    narrow string, thereby avoiding unnecessary allocations. It is similarly
    possible to decode directly into a WString result in the unescape functions, but
    it would increase branchiness and complexity of the code in order to handle
    sequences of 2, 4, or 8 hex characters per wide char instead of just appending
    all UTF-8 bytes and then widening the string at the end of the operation.

2023-04-29 04:44 UTC, mqudsi commented on fish-rust/src/common.rs
> -            prev_was_hex_encoded = false;
Unless I'm missing something, this was unreachable.

2023-04-29 04:46 UTC, mqudsi commented on fish-rust/src/common.rs
> -                i += 1;
This doesn't correspond to the escape code - a `%` is encoded as `%25` and not `%%`.

2023-04-29 05:36 UTC, mqudsi commented on fish-rust/src/common.rs
> -    let narrow = wcs2string(input);
It's not necessary to narrow the whole string upfront.

2023-04-29 05:37 UTC, mqudsi commented on fish-rust/src/common.rs
> -    let narrow = wcs2string(input);
It's not necessary to narrow the whole string upfront.

2023-04-29 05:37 UTC, mqudsi commented on fish-rust/src/common.rs
> -            if c.is_alphanumeric() || [b'/', b'.', b'~', b'-', b'_'].contains(&byte) {
The first equivalent of "is ascii" check is not needed since we can check directly for the chars we want.

2023-04-29 05:43 UTC, mqudsi commented on fish-rust/src/common.rs
> +            }
I think this else block might not have been caught/enforced previously?

2023-04-29 17:30 UTC, mqudsi commented on fish-rust/src/common.rs
> +            out += &sprintf!(L!("%%%02X"), byte)[..];
I was very much tempted to use native rust to format then manually widen the result to avoid an allocation - thanks for making that change!

2023-04-29 17:31 UTC, mqudsi commented on fish-rust/src/common.rs
> +    for c in input.as_char_slice() {
Thanks; I'll change it.

I could have sworn that's what I tried but either the compiler or rust-analyzer didn't like it for wsr/WString.

2023-04-29 18:42 UTC, ridiculousfish requested changes
This changes the behavior from its current locale-sensitive encoding to UTF-8. Is there a reason to make such a change? It is potentially breaking.

2023-04-29 19:00 UTC, mqudsi commented
There are a few issues I could see:

For variable and url escaping: 
* the previous approach resulted in non-stable output, meaning if someone used `fish escape --style=var/url` on their end then copy-and-pasted the result into a script, unescape might fail when that script is executed on another PC, or if the user used it on their own PC but tried to unescape the result with a different locale, it would fail.
* the code can't handle special characters with an ascii or other restricted locale, which seems like it would actually be one of the very reasons to escape things, e.g. trying to unescape with locale set to C
* a modern cli app that *isn't* locale aware (and few are, these days) is probably going to generate non-ascii output as UTF-8, so if you try to escape the output of an external command but your locale is missing the characters/codepoints in question, escaping then unescaping will be a lossy operation. (Same goes for extracting text content from a file and then escaping the result)

For url escaping:
* The biggest issue is that it's extremely unlikely to be able to actually *use* the escaped URL if your locale isn't UTF-8. It's fine (except for the issues above) when you're using fish to both escape and unescape the URL, but if you try to `curl` the resulting escaped URL or copy-and-paste it into your web browser, the server is going to (with 99% probability) use UTF-8 to decode the hex-escaped URL sequences and it'll either be an invalid result or not the intended result. That's probably the main usage of `string escape --style=url` since I don't think anyone is going to be implementing both the http client *and* the http server in fish, so it's important to use the standardized encoding to generate the escaped url.

2023-04-29 19:05 UTC, mqudsi commented
Actually, you can ignore what I said above because it's besides the point: this is only a breaking change *for the cases that were already broken*. 

i.e. transiently escaped then unescaped contetn in the same session that worked fine before will continue to work fine (because before the same locale was used to encode and decode, assuming it didn't change mid-session, and now a different but fixed locale is used to encode and decode). 

The only cases that *will* break are cases where the output of `string escape` is persisted beyond a single fish session, meaning these were cases where the user could have changed locales between escaping and unescaping,  *or* the escaped content was being sent to another machine for unescaping and previously there was no guarantee that locales would line up on both ends. 

There is nothing I can think of that will break if we change to fixed UTF-8 that wasn't already possibly broken.

2023-04-29 19:23 UTC, ridiculousfish commented
Yes, these functions are broken and their behavior makes no sense. But that doesn't matter now: the goal of the rewrite is to preserve existing behaviors.

> The only cases that will break are cases where the output of string escape is persisted beyond a single fish session 

That's more than enough reason to avoid this. For example, abbreviations stored in universal variables use the "variable" escape style (perhaps the only usage). This change therefore could potentially break abbreviations.

IMO these functions are not worth "fixing." We should instead deprecate them. But if we do decide to fix them, it will be a breaking change, and that should be a separate effort from the Rust port.

2023-04-29 19:43 UTC, mqudsi commented
I'm fine with tabling this until after the port but my point is that starting fish *today* with a different locale will cause the abbreviations to fail to load since the unescape no longer lines up. As it's already broken, this can only help.

2023-05-22 15:19 UTC, faho commented
>starting fish today with a different locale will cause the abbreviations to fail to load since the unescape no longer lines up.

That's just for the *variables*, which are deprecated.

>I'm also unclear on how we could drop them since they serve a real purpose (even if we end up not using them internally).

We do expose all of these escaping styles, via `string escape`.

The URL-escaping specifically is used in [our OSC7 cwd-reporting](https://github.com/fish-shell/fish-shell/blob/21e31c9b595256ea08715a5a7f37d83b78efc764/share/functions/__fish_config_interactive.fish#L277), and a few other escapes are also defined as taking URLs, including OSC8 for hyperlinks and [iTerm's RemoteHost escape](https://iterm2.com/documentation-escape-codes.html). I don't believe there is a good generally available portable command alternative for this.

`regex` escaping is used for `string match` and `string replace`, and is *necessary* if you want to match a dynamic string properly - otherwise if you got `foo.*` it would suddenly be treated as a regex! (an alternative design would allow placeholders in the regex)

`script` escaping is needed for `eval` and friends, but also e.g. for `fish_command_not_found`'s output - so we can tell you "that's the command that failed" without it bleeding over into the containing string.

We currently use `var` escaping only in the git-completions, to cache git aliases. Before we used to use it in the abbr function (and we still do in the importing code for old-style variables). All of this is a workaround for dictionaries.

I don't believe we can remove or deprecate any of these. Var-style is closest, but it's still an awkward compatibility break and I do not believe it really hurts.

2023-05-22 16:37 UTC, mqudsi commented
> We do expose all of these escaping styles, via `string escape`.

That's the point I was trying to make. We expose them for a reason and people (us and others) use them for good reason.

2023-09-26 08:26 UTC, faho commented
I'm closing this because it has conflicts and I'm not quite sure what the current state is.

2023-09-26 08:26 UTC, closed without merging